### ISSUE TITLE
Doesn't seem to work with Regolith's latest releas

### ISSUE THREAD

**Issue by j-maynard** [lacerda/regolith-kde#1]
I thought I would raise an issue to say this looks like awesome work but doesn't seem to work with the latest releases from Regolith.  The main issue is the status bar displays the error "Error: Status command process exited unexpected (exit: 139)".  Also no desktop background image.  So my guess is things like the XResource files aren't loading properly.

**Comment by lacerda** [comment]
Thanks for the report @j-maynard ! I've moved on to a different environment since then, so I'll archive this repo to prevent further confusion.
